version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run:
                            name: install
                            command: yarn install
                      - run:
                            name: lint
                            command: yarn lint
                      - run:
                            name: test
                            command: yarn test
                      - run:
                            name: build
                            command: yarn build
workflows:
    build-and-test:
        jobs:
            - build
