version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: yarn install
    lint:
        executor:
            name: node/default
        steps:
            - node/with-cache:
                  steps:
                      - run: yarn lint
    test:
        executor:
            name: node/default
        steps:
            - node/with-cache:
                  steps:
                      - run: yarn test
workflows:
    build-lint-test:
        jobs:
            - build
            - lint:
                  requires:
                      - build
            - test:
                  requires:
                      - build
