version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache: # Use node orb's caching of node_modules
                  cache-key: yarn.lock
                  steps:
                      - run: yarn install
            - run:
                  name: Type check and lint
                  command: yarn lint
            - run:
                  name: Test
                  command: yarn test
            - run:
                  name: Build
                  command: yarn build
workflows:
    test-and-build:
        jobs:
            - build
